### ISSUE TITLE
`source-dir` does not resolve absolute paths

### ISSUE THREAD

**Issue by marshall007** [wercker/step-s3sync#18]
Currently, the supplied `source-dir` is naively concatenated with `WERCKER_ROOT` instead of properly resolving the path. This prevents you from using absolute paths like `WERCKER_OUTPUT_DIR` as the `source-dir`. Example:

```yml
deploy:
  steps:
    - s3sync:
        key-id: $AWS_ACCESS_KEY_ID
        key-secret: $AWS_SECRET_ACCESS_KEY
        bucket-url: $BUCKET
        # ends up being "/pipeline/source//pipeline/output"
        source-dir: $WERCKER_OUTPUT_DIR
```
